
# Folgt {#day6}

```{r include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{r,echo=FALSE}
## Morning session: 
# The jelly bean problem:
# How do p-values behave if there is NO difference 
# ("under the null hypothesis"):

# How often do we commit a type I error 
# (= claiming that there is a difference 
# although there is none)?

# What is the specificity
# (= the probability to realize that there is 
# no difference if there is none)?


# How do p-values behave if there is
# a real difference:


# How often do we commit a type II error
# (= claiming that there is NO difference 
# although there is one)?


# What is the sensitivity
# (= the probability to detect the 
# difference, also called "power")?


# Power analysis: How likely is it to miss
# a true effect?



# With Power analysis, I can estimate a sample size
# BEFORE performing the experiment:


## Afternoon session: 
# How to handle files
# that are not correctly formated:

# How to handle multiple files in a loop:

```


## Non Linear Least Squares Fitting

```{r, eval = FALSE, echo = FALSE}
PurTrt <- Puromycin[ Puromycin$state == "treated", ]

michaelis_menten_fun <- function(conc, Vm, K) {
  (Vm * conc) / (K + conc)
}

plot(PurTrt$conc, PurTrt$rate)
curve(michaelis_menten_fun(conc = x, Vm = 200, K = 0.06),
      add = TRUE,
      col = 'red',
      from = 0, to = 1,
      n = 100)

model <- nls(rate ~ michaelis_menten_fun(conc, Vm, K),
          start = list(Vm = 200, K = 0.1), data = PurTrt)


x0 <- seq(min(PurTrt$conc), max(PurTrt$conc), length = 50)
y0 <- predict(model, newdata = list(conc = x0))
plot(PurTrt$conc, PurTrt$rate)
lines(x0, y0, col = 'red')


```


